### ISSUE TITLE
Did you know how to avoid "String" type field "None" values become "false"

### ISSUE THREAD

**Issue by lmarklil** [ajepe/odoo-addons#15]
![image](https://user-images.githubusercontent.com/24407073/57360202-20cb0380-71ac-11e9-9524-e72ec2772188.png)

**Comment by Matt-OBell** [comment]
A None value in python means that a variable is empty, which is also the same thing in Javascript as falsy value.

**Comment by ajepe** [comment]
A None value in python means that a variable is empty, which is also the same thing in Javascript as falsy value.

**Comment by lmarklil** [comment]
Well, thanks for your response. But I think it's unreasonable to set None value as 'false' in JSON, it should be null.
